### PR TITLE
[FIX]8.0 binder patch

### PR DESCRIPTION
**Pull request by flotho**
Hi,

This one depends on :
- [ ] https://github.com/pedrobaeza/connector-prestashop/pull/18

I'm also working with the latest OCA/connector to test this

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@mikelarre, check this one also after the other.

**Comment by flotho** [comment]
hi @mikelarre, @pedrobaeza 

could you also give me the commit you're using on the OCA/connector?
Personnaly, this one https://github.com/OCA/connector-prestashop/pull/11#issuecomment-133880810 seems to be working.
If you give me yours, I'll work on it in the same time

**Comment by pedrobaeza** [comment]
Yeah, that one is the most updated for us.

**Comment by flotho** [comment]
@pedrobaeza ,
I'm debugging a lot some parts of the code. Which strategy do you recommend to me? Creating PR in cascade with dependencies? Will it be easy for you?
Creating many branches will be a mess for me if they are not in cascade.
Thanks for your advice

**Comment by flotho** [comment]
forget this one, it seems that I wasn't working on the correct OCA version, so with original code it works

**Pull request closed without merging**
