### PR TITLE
8.0 mig image issue

### PR DESCRIPTION
**Pull request by flotho**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@mikelarre, can you please review this change?

**Comment by flotho** [comment]
Hi @pedrobaeza 
I'm not sure to do right.
I pushed another PR : https://github.com/pedrobaeza/connector-prestashop/pull/7 but it uses commits presents in this PR.
Will it be a problem for you later?

**Comment by pedrobaeza** [comment]
Well, you can start each branch from the original unchanged one, but if there's any dependency, then you can say that one depends on the other and the previous should be merged first.

**Comment by flotho** [comment]
And how can I indicate this dependency? Litterraly in the github PR ?

**Comment by pedrobaeza** [comment]
Yeah, it's only a note on the PR for the reviewers.

**Comment by flotho** [comment]
ok, perfect

**Comment by mikelarre** [comment]
Changes made in this PR are required if you don't use the fork of prestapyt made by akretion, as this fork uses 'requests' python library instead of 'httplib2' that uses the original one. Take into account that akretion is the original developer of the module.

**Comment by flotho** [comment]
Hi @mikelarre 
I'm using prestapyt `prestapyt (0.6.2)` coming from a simple `pip install` . It's is also what is it recommend in https://github.com/akretion/prestapyt 
Am I doing wrong?

regards

**Comment by mikelarre** [comment]
https://github.com/akretion/prestapyt is the fork of https://github.com/guewen/prestapyt. If you use pip to install it you are using the last one (https://pypi.python.org/pypi/prestapyt/0.6.2).

**Comment by flotho** [comment]
this is exactly what I've done, I simply use `pip`
So is my conf correct regarding to you?
Does this PR could be considered as valid?
regards

**Comment by mikelarre** [comment]
Sorry, It seems that I am not explaining properly.
If you install the library doing `pip install prestapyt` you will install a version that we are not using.
To install the same version we are using you should download the fork in https://github.com/akretion/prestapyt and them install it by doing `python setup.py install` and previously don't forget to uninstall by executing `pip uninstall prestapyt`

Take into account that akretion uses this fork and not the library in pip repositories (which is the one you have installed).

**Comment by flotho** [comment]
Okaaayyyy, I was also wondering if I was doing well.
I'll do as you proposed and let you know.

**Comment by pedrobaeza** [comment]
@mikelarre, anyway, why pip version is not valid? We should then ask for pushing akretion version to pip instead

@sebastienbeau can you help us to promote your version to pip?

**Comment by flotho** [comment]
:+1:

**Comment by mikelarre** [comment]
The module of prestashoperpconnect uses this prestapyt fork from akretion. The fork started years ago and has so many changes
First of all it uses other libraries, as an example the one mentioned before **requests**, and that is  why we have this conversation :wink: . Second there are changes in functions, in parameters passed to them and in the response of these, so that the management of these responses changes. I do not think it is easy to make them compatible. If there are any working instances, this could cause many unexpected problems.

**Comment by flotho** [comment]
Hi @mikelarre, once installing the repo the version I get is :

```
pip list | grep prest
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
prestapyt (0.4.0)
```

Do you confirm?
regards

**Comment by mikelarre** [comment]
I think is right. The version on setup.py file is the same. If you want to be sure, follow the steps listed above.

Sorry for the delay

**Comment by flotho** [comment]
No problem, Thanks

**Comment by flotho** [comment]
@mikelarre are you sure of the version of the lib?
When trying to import metadatas I have this message :

```
/usr/lib/python2.7/site-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py:164: UserWarning: This library may not be compatible with this version of PrestaShop (1.5.6.2). Please upgrade/downgrade this library
```

**Comment by mikelarre** [comment]
it is the correct one. This library hasn't been updated in a long time

**Comment by flotho** [comment]
Ok, this one is useless with the correct prestapyt

**Pull request closed without merging**
