### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by flotho**
https://travis-ci.org/OCA/connector-prestashop/jobs/76316807

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can directly remove it if you want. It was only and all debug traces. In the last version, this is for sure removed, but the one that implements it (@mikelarre) is on holidays. When he comes back, he'll push this last version.

**Comment by pedrobaeza** [comment]
You should move also the rest of the files (backend.py and so on)

**Comment by flotho** [comment]
Hi @pedrobaeza 
Could you explain me what could be the side effects of this. 
For example there is already an account.py, product.py and so on in the root of the module AND in the models folder.
I can see that both haven't the same structure so what could be the best way to organise this part of code?
Regards

**Comment by pedrobaeza** [comment]
There's no side effect if you don't alter the existing classes. Just blend both files.

**Comment by flotho** [comment]
you mean merge the files? Right?

**Comment by pedrobaeza** [comment]
Yeah

**Comment by flotho** [comment]
Hi @pedrobaeza 
I pushed some changes here. Any chance to be reviewed?

**Comment by pedrobaeza** [comment]
Did you move the files with `git mv`? Because diff is too big for the made changes.

**Comment by flotho** [comment]
Oups...
I'm a little new to git part. I'm coming from the svn world. Sorry I didin't use the git mv command.
Doo you want me to revert and use it once more?
regards

**Comment by pedrobaeza** [comment]
Yes, please, that way the diff would be easier to check for any possible problem.

**Comment by flotho** [comment]
Great, a good reason to learn new git parts.... ;-)
I'll let you know

**Comment by flotho** [comment]
Hi @pedrobaeza 
I pushed only a little change so that you validate that's the kind of PR easy for you to vallidate.
Let me know if it's OK.
FYI, the *_backend files are used temporary before merging files.

**Comment by pedrobaeza** [comment]
Well, there's still a lot of diff in files and you have sum the amount of 30 commits! Can you squash them into  less or start a new clean PR?

**Comment by flotho** [comment]
Hi @pedrobaeza 
I'm definitively not efficient enough on that part, I was expecting to do it step by step.
I'm not aware of Managing Pull Request in Github, so I can easily imagine that's not so easy for you if there is too many commits.
I will recreate another PR and redo it

**Comment by flotho** [comment]
Hi @pedrobaeza 
I'm not sure that's Ok but I squash multiple commits in one.
How does it appears for you in the PR validation?
Do you prefer another PR?
regards

**Comment by pedrobaeza** [comment]
Now there are 32 commits. I'm afraid you're not doing the right way.

**Comment by flotho** [comment]
replace by https://github.com/pedrobaeza/connector-prestashop/pull/5

**Pull request closed without merging**
