### PR TITLE
[REF]8.0 Littles fixes licence and file names

### PR DESCRIPTION
**Pull request by flotho**
use absolute imports in preparation of next refactorings

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's no need for absolute imports. You can still use relative imports although you change file paths. You can even use `..` (two points) for pointing to files in the upper directory.

**Comment by flotho** [comment]
You're right but I had an issue with this a a few days before.
And the advice was to use the absolute import. That is the reason.

**Comment by pedrobaeza** [comment]
I see no reason for that, really. That advise could come in a preventive way, but there's no really danger on it. If you explain me the issue, I can tell you what is the real problem.

**Comment by flotho** [comment]
Here was the reason : 
https://www.odoo.com/fr_FR/forum/help-1/question/how-to-launch-connector-with-multi-worker-49235#answer_61061
Maybe it's not necessary but as I'm also a java developper, I'm used to reference without any point the class inside the same package and fully referenced other modules/packages.
Is it problematic for merging?

**Comment by pedrobaeza** [comment]
That advise is not very advisable to follow :laughing: There's no such possibility on Odoo of confusing paths because the management is done inside Odoo and not Python itself. You only need absolute path when referring files from other modules, but not your own module. The rest is a bad installation/configuration in your system. I prefer not to make these changes because the code is read worst this way.

**Comment by flotho** [comment]
snif... I definitively do wrong...
I reset and squash commit for you

**Comment by flotho** [comment]
@pedrobaeza is it better for this one?

**Comment by pedrobaeza** [comment]
You still continue adding more and more commit, why?

**Comment by flotho** [comment]
hi @pedrobaeza, thanks for your comments 
I probably do this because I'm not mastering enough git so that all my commits are turned into one. Is it what we are talking about?
To be sure on the PR, as you won't validate the absolute import and as you'll like me to squash licences commit, in the end this PR should have only a single commit. Am I right?
If so how can I do this with git. I tried to rebase -i for squashing and it adds more and more commits. I also tried to revert / reset but it adds in the history.
Your advice will be appreciated so that I could push the many changes I made
regards

**Comment by flotho** [comment]
should be better now?

**Comment by flotho** [comment]
@pedrobaeza 
Is this one enough detailed?
Many other PR are depending on this one. Tell me what you need.
regards

**Comment by pedrobaeza** [comment]
I still see absolute imports, changes that makes this breaks (you change **init**.py to point to models, but there's no models), and so on. @mikelarre has prepared all the changes made an is going to propose a new PR. The best thing is to merge that one and clean myself the branch.

Thanks anyway for your efforts.

**Comment by flotho** [comment]
@pedrobaeza, @mikelarre, you're welcome,

Additionnaly, you're right I fixed some absolute imports in later PR and that's unfair for you ;-)
Anyway, did @mikelarre could take this on https://github.com/pedrobaeza/connector-prestashop/pull/13 into account
regards

**Comment by flotho** [comment]
Hi, so it's probably better for me to fork the @mikelarre PR, an propose on its repo?
Am I right?

regards

**Comment by pedrobaeza** [comment]
I have already merge his changes, so you can start from my branch

**Comment by flotho** [comment]
damned, I'm lost, as far as I can see, its PR is not merged : https://github.com/pedrobaeza/connector-prestashop/pull/14
So what branch should I use for pushing my modif?

**Comment by pedrobaeza** [comment]
Sorry, I forgot to click the button. Now it's done

**Comment by flotho** [comment]
pfiouuu, I was about to scream ;-)

**Pull request closed without merging**
